/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_luismontalvan;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luism
 */
public class Lab6P2_LuisMontalvan extends javax.swing.JFrame {

    /**
     * Creates new form Lab6P2_LuisMontalvan
     */
    public Lab6P2_LuisMontalvan() {
        initComponents();
        jPSignup.setVisible(false);
        jPHomePage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHomePage = new javax.swing.JPanel();
        jPLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFUserLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFContrasenaLogin = new javax.swing.JTextField();
        jBtnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPSignup = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFCrearUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFCrearContraseña = new javax.swing.JTextField();
        jBtnSignin = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSEdad = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jCBtipoUsuario = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPHomePageLayout = new javax.swing.GroupLayout(jPHomePage);
        jPHomePage.setLayout(jPHomePageLayout);
        jPHomePageLayout.setHorizontalGroup(
            jPHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPHomePageLayout.setVerticalGroup(
            jPHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("Iniciar Sesión");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        jTFContrasenaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFContrasenaLoginActionPerformed(evt);
            }
        });

        jBtnLogin.setText("Entrar");
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseClicked(evt);
            }
        });

        jLabel1.setText("¿No tienes cuenta?");

        jButton2.setText("Crear Cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPLoginLayout = new javax.swing.GroupLayout(jPLogin);
        jPLogin.setLayout(jPLoginLayout);
        jPLoginLayout.setHorizontalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addComponent(jLabel10)
                .addGap(1, 1, 1))
            .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPLoginLayout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jLabel2))
                        .addComponent(jLabel3)
                        .addComponent(jTFUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jTFContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPLoginLayout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPLoginLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButton2))
                        .addGroup(jPLoginLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPLoginLayout.setVerticalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPLoginLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel2)
                            .addGap(55, 55, 55)
                            .addComponent(jLabel3)
                            .addGap(5, 5, 5)
                            .addComponent(jTFUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(jLabel4)
                            .addGap(5, 5, 5)
                            .addComponent(jTFContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1)
                            .addGap(5, 5, 5)
                            .addComponent(jButton2))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Crear Cuenta");
        jPSignup.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel7.setText("Usuario");
        jPSignup.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPSignup.add(jTFCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 230, -1));

        jLabel8.setText("Contraseña");
        jPSignup.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTFCrearContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCrearContraseñaActionPerformed(evt);
            }
        });
        jPSignup.add(jTFCrearContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, -1));

        jBtnSignin.setText("Crear Cuenta");
        jBtnSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSigninMouseClicked(evt);
            }
        });
        jBtnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSigninActionPerformed(evt);
            }
        });
        jPSignup.add(jBtnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jLabel11.setText("Edad");
        jPSignup.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 40, -1));

        jSEdad.setModel(new javax.swing.SpinnerNumberModel(18, 0, 120, 1));
        jPSignup.add(jSEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, -1));

        jLabel9.setText("Tipo de Usuario");
        jPSignup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jCBtipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oyente", "Artista" }));
        jPSignup.add(jCBtipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 99, -1));
        jPSignup.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 0, 250, 500));
        jPSignup.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));

        getContentPane().add(jPSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFContrasenaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFContrasenaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFContrasenaLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTFCrearContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCrearContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCrearContraseñaActionPerformed

    private void jBtnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSigninActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       jPLogin.setVisible(false);
       jPSignup.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jBtnSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSigninMouseClicked
        String tipoU = (String)jCBtipoUsuario.getSelectedItem();
        int edad = (Integer)jSEdad.getValue();
        AdministrarUsuarios ap = new AdministrarUsuarios();
        ap.administrarUsuarios("./Usuarios");
        ap.cargarArchivo();
        Artista artista = new Artista();
        Oyente oyente = new Oyente();
        try{
            
            
        if(edad>=18){
            
            if (tipoU.equalsIgnoreCase("Artista")) {
                
                artista.setnUsuario((String)jTFCrearUsuario.getText());
                artista.setContrasena((String)jTFCrearContraseña.getText());
                artista.setEdad(edad);
                artista.setTipoUsuario(tipoU);
               
            }else{
                
                String nombre = (String)jTFCrearUsuario.getText();
                String contrasena = (String)jTFCrearContraseña.getText();
                usuarios.add(new Oyente(nombre, tipoU, contrasena, edad));
            }
            JOptionPane.showMessageDialog(jPSignup, "Usuario creado exitosamente");
        }else if(edad>=12){
            
            if(tipoU.equalsIgnoreCase("Oyente")){
                String nombre = (String)jTFCrearUsuario.getText();
                String contrasena = (String)jTFCrearContraseña.getText();
                usuarios.add(new Oyente(nombre, tipoU, contrasena, edad));
                JOptionPane.showMessageDialog(jPSignup, "Usuario creado exitosamente");
            }else{
              JOptionPane.showMessageDialog(jPSignup, "Edad no valida");  
            }
        }else{
            JOptionPane.showMessageDialog(jPSignup, "Edad no valida");
        }
        }catch(Exception e){            
        }
        ap.getListaUsuarios().add(artista);        
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Lab6P2_LuisMontalvan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBtnSigninMouseClicked

    private void jBtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseClicked
        AdministrarUsuarios ap = new AdministrarUsuarios();
        ap.administrarUsuarios("./Usuarios");
        ap.cargarArchivo();
        int bandera,pos = 0;
        for (Usuario u : ap.getListaUsuarios()) {
            String utemp= u.getnUsuario();
            if(jTFUserLogin.equals(utemp)){
                //pos= ap.getListaUsuarios().indexOf(u);
                
                String ctemp = u.getContrasena();
                if(jTFContrasenaLogin.equals(ctemp)){
                    jPHomePage.setVisible(true);
                }
            }
            
        }
        System.out.println(ap.getListaUsuarios().ge);
    }//GEN-LAST:event_jBtnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_LuisMontalvan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6P2_LuisMontalvan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JButton jBtnSignin;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBtipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPHomePage;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPanel jPSignup;
    private javax.swing.JSpinner jSEdad;
    private javax.swing.JTextField jTFContrasenaLogin;
    private javax.swing.JTextField jTFCrearContraseña;
    private javax.swing.JTextField jTFCrearUsuario;
    private javax.swing.JTextField jTFUserLogin;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> usuarios = new ArrayList();
}
